package model;

import java.time.LocalDateTime;

public class Profile {

    // Fields
   
    private Integer       id;                // Auto-generated by the database (null before saving)
    private String        name;              // Display name chosen by the user
    private Currency      defaultCurrency;   // The user's preferred currency (enum — never a raw String)
    private LocalDateTime createdAt;         // Set once at creation time, never changed after

   
    // Default constructor
    
    public Profile() {
    }

    // Parameterized constructor

    public Profile(String name, Currency defaultCurrency, LocalDateTime createdAt) {
        this.name            = name;
        this.defaultCurrency = defaultCurrency;
        this.createdAt       = createdAt;
    }

    // Full constructor

    public Profile(Integer id, String name, Currency defaultCurrency, LocalDateTime createdAt) {
        this.id              = id;
        this.name            = name;
        this.defaultCurrency = defaultCurrency;
        this.createdAt       = createdAt;
    }

    // Getters & Setters

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Currency getDefaultCurrency() {
        return defaultCurrency;
    }

    public void setDefaultCurrency(Currency defaultCurrency) {
        this.defaultCurrency = defaultCurrency;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        return "Profile {"
                + " id="              + id
                + ", name='"          + name            + "'"
                + ", defaultCurrency=" + defaultCurrency  // calls Currency.toString()
                + ", createdAt="      + createdAt
                + " }";
    }
}